[project]
name = "version-2-0-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "mysql-connector-python>=26.7.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.53",
    "unicorn>=2.1.4",
    "uvicorn[standard]>=0.53.0",
]
